# Generated by Django 5.0.4 on 2024-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
